SDKVERSION = 7.0
ARCHS = armv7 arm64

include theos/makefiles/common.mk

APPLICATION_NAME = Envader
Envader_FILES = main.m EnvaderApplication.mm RootViewController.mm
Envader_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/application.mk
